import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navigation from "./components/navigation/Navigation";
import Footer from "./components/footer/Footer";
import { Toaster } from "react-hot-toast";
import CartProvider from "./components/cart/CartProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <CartProvider>
        <html lang="en">
          <body className={inter.className}>
            <Navigation />
            {children}
            <Toaster position="top-right" />
            <Footer />
          </body>
        </html>
      </CartProvider>
    </ClerkProvider>
  );
}
